from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
import io

def generate_pdf_report(company_name, sector, ratios, score, label):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                            rightMargin=inch, leftMargin=inch,
                            topMargin=inch, bottomMargin=inch)

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle('Title', parent=styles['Title'],
                                  fontSize=20, textColor=colors.HexColor('#1a1a2e'))
    elements.append(Paragraph(f"Benchmarking Report", title_style))
    elements.append(Paragraph(f"{company_name}", title_style))
    elements.append(Spacer(1, 0.2 * inch))

    # Subtitle
    elements.append(Paragraph(f"Sector: {sector}", styles['Normal']))
    elements.append(Paragraph(f"Generated by Eelanos BSE Benchmarking Portal", styles['Normal']))
    elements.append(Spacer(1, 0.3 * inch))

    # Benchmark Score
    score_style = ParagraphStyle('Score', parent=styles['Normal'],
                                  fontSize=14, textColor=colors.HexColor('#2ecc71'))
    elements.append(Paragraph(f"Overall Benchmark Score: {score}/100 — {label}", score_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Ratios Table
    elements.append(Paragraph("Financial Ratios", styles['Heading2']))
    elements.append(Spacer(1, 0.1 * inch))

    table_data = [
        ["Metric", "Value"],
        ["Net Margin", f"{ratios.get('net_margin', 'N/A')}%"],
        ["EBITDA Margin", f"{ratios.get('ebitda_margin', 'N/A')}%"],
        ["ROCE", f"{ratios.get('roce', 'N/A')}%"],
        ["Debt / Equity", f"{ratios.get('debt_to_equity', 'N/A')}x"],
        ["ROE", f"{ratios.get('roe', 'N/A')}%"],
    ]

    table = Table(table_data, colWidths=[3 * inch, 3 * inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#f8f9fa'), colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('FONTSIZE', (0, 1), (-1, -1), 11),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.3 * inch))

    # Footer
    elements.append(Spacer(1, 0.5 * inch))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                   fontSize=9, textColor=colors.grey)
    elements.append(Paragraph("Confidential — Prepared by Eelanos Analytics Platform", footer_style))
    elements.append(Paragraph("Data sourced from BSE-listed company financials via Screener.in", footer_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer